version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    container_name: db_jonction
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jonction
      MYSQL_USER: jonction
      MYSQL_PASSWORD: jonction
    ports:
      - "3307:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_jonction
    restart: always
    depends_on:
      - database
    ports:
      - "8082:80"
    environment:
      PMA_HOST: database
      PMA_USER: jonction
      PMA_PASSWORD: jonction
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_jonction
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8083:80"
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: